### ISSUE TITLE
Sugestão para a descrição

### ISSUE THREAD

**Issue by giovanaBritoOliveira** [joaobb/Tender#18]
Projeto muito massa! Só uma dica: colocar na descrição do projeto já as funcionalidades do back e telas do front. Isso vai facilitar até na hora de codar e no gerenciamento do projeto. Além de informar melhor a quem tá vendo de fora teu projeto. :)

**Comment by joaobb** [comment]
Obrigado @giovanaBritoOliveira. 
Sobre as telas do front, eu ainda estou pensando em como ficarão, por isso não adicionei essas no repositório.
Mas vlw mesmo pelos toques, tentarei adicionar mais informações nas próximas iterações.
