### ISSUE TITLE
Componente Input.

### ISSUE THREAD

**Issue by MisaelAugusto** [joaobb/Tender#25]
Na sua pasta de componentes você tem o componente Input, porém dentro dele tem 3 componentes diferentes para cada tipo de input. A ideia de criar componentes é de reutilizá-los, então seria interessante que só existisse apenas um componente input, que recebe todas as propriedades que você utiliza em cada um deles (ícone, tipo do input, etc.). Assim, você consiguiria utilizar um único componente <Input /> em qualquer lugar da aplicação.

**Comment by joaobb** [comment]
Opa @MisaelAugusto, bom toque. Irei fazer essas mudanças, mas apenas nos `TextualInput` e `EmailInput`. Pois,  o `PasswordInput` possui uma lógica de visibilidade que não se encaixaria nos outros.

**Comment by joaobb** [comment]
Alteração realizada no commit https://github.com/joaobb/Tender/commit/920bd8d34c91132a92aae52c2031ec3dc181a467
